export const QuizData = [
  {
    question_id: 0,
    question: "Which one of these is the world's largest dam?",
    options: [
      {
        id: "option_1",
        answer: "	Tarbela Dam",
        status: false,
      },
      {
        id: "option_2",
        answer: "Fort Peck Dam",
        status: false,
      },
      {
        id: "option_3",
        answer: "Atatürk Dam",
        status: false,
      },
      {
        id: "option_4",
        answer: "The Three Gorges Dam",
        status: false,
      },
    ],
    status: false,
    correct_answer: "3",
    answer_description: "The Three Gorges Dam",
    image: false,
    image_path: "",
    isVisited: true,
    unanswered: true,
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
    selected: null,
  },
  {
    question_id: 1,
    question: "What Do You Drink That Comes From A Cow?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Refermilk",
        status: false,
      },
      {
        id: "option_2",
        answer: "Qawsz",
        status: false,
      },
      {
        id: "option_3",
        answer: "Qazxsw",
        status: false,
      },
      {
        id: "option_4",
        answer: "Used",
        status: false,
      },
    ],
    status: false,
    correct_answer: "2",
    answer_description: "cow gives us milk",
    image: false,
    isVisited: false,
    unanswered: true,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
    selected: null,
  },
  {
    question_id: 2,
    question: "How Many Vowels Are There In The English Alphabet (Algebra  E)",
    options: [
      {
        id: "option_1",
        answer: "5",
        status: false,
      },
      {
        id: "option_2",
        answer: "6",
        status: false,
      },
      {
        id: "option_3",
        answer: "23",
        status: false,
      },
      {
        id: "option_4",
        answer: "1",
        status: false,
      },
    ],
    status: false,
    correct_answer: "3",
    answer_description: "ENGLISH EXPLANATION",
    image: false,
    isVisited: false,
    unanswered: true,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
    selected: null,
  },
  {
    question_id: 3,
    question: "What Animal Goes “Moo”?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Cow",
        status: false,
      },
      {
        id: "option_2",
        answer: "Goat",
        status: false,
      },
      {
        id: "option_3",
        answer: "Both",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: "1",
    answer_description: "cow says it",
    image: false,
    isVisited: false,
    unanswered: true,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
    selected: null,
  },
  {
    question_id: 4,
    question: "Which Animal Is Known As The King Of The Jungle?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Lion",
        status: false,
      },
      {
        id: "option_2",
        answer: "Ased",
        status: false,
      },
      {
        id: "option_3",
        answer: "Usedwasderf",
        status: false,
      },
      {
        id: "option_4",
        answer: "Rfdfff",
        status: false,
      },
    ],
    status: false,
    correct_answer: "2",
    answer_description: "lion is the king of jungle",
    image: false,
    isVisited: false,
    unanswered: true,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
];
